# Generated by Django 5.1.4 on 2025-01-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='status',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
