# Generated by Django 5.1.4 on 2024-12-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_remove_medicament_duree_remove_medicament_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='laborantin',
        ),
        migrations.RemoveField(
            model_name='bilanbiologique',
            name='result',
        ),
        migrations.AddField(
            model_name='bilanbiologique',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bilans', to='utilisateurs.medecin'),
        ),
    ]
