# Generated by Django 5.1.4 on 2024-12-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_remove_bilanbiologique_laborantin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilanbiologique',
            name='resultat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
